# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b01d6b95a04fba38a37f5f8555e26eace075609a6dfebe1e81bbade5a4b3e99c027a616a5f5c64e7df2190bfc6a253f7a69382457fa58881de015242d418b25

test:
  secret_key_base: 78475ec73e9dd5e0acd251aa6fc52e53cfe56b8220557c6f33bd88aec20c692c0497882c8eed99494817e30bfda3f4a5cb4b0426d663828f64195c8b515b55b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
